# Generated by Django 4.2.20 on 2025-04-05 08:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('bidder', models.CharField(max_length=150)),
                ('auction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Bid', to='auctions.auction')),
            ],
            options={
                'ordering': ('id',),
            },
        ),
    ]
