# Generated by Django 5.2 on 2025-04-08 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_bid'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bid',
            options={'ordering': ['-price']},
        ),
        migrations.AlterField(
            model_name='bid',
            name='price',
            field=models.PositiveIntegerField(),
        ),
    ]
