# Generated by Django 5.2 on 2025-04-12 13:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0004_auction_auctioneer"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bid",
            name="auction",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bids",
                to="auctions.auction",
            ),
        ),
    ]
