# Generated by Django 5.2 on 2025-05-10 14:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0008_comment"),
    ]

    operations = [
        migrations.AddField(
            model_name="auction",
            name="rating",
            field=models.DecimalField(decimal_places=2, default=1, max_digits=3),
            preserve_default=False,
        ),
    ]
