# Generated by Django 5.2 on 2025-05-10 14:53

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0009_auction_rating"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="auction",
            name="rating",
        ),
    ]
