# Generated by Django 5.2.1 on 2025-05-12 12:07

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0011_alter_auction_thumbnail"),
    ]

    operations = [
        migrations.AlterField(
            model_name="auction",
            name="thumbnail",
            field=models.URLField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
